# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b8ed430e5d2fc80294b459c0fb7e46e9aa4c97392c527b1d5108244512f81c577d2b65f06e1a9a7496d270be3c4b103ae8fe5d959e7dccfaa570e03f46555c8

test:
  secret_key_base: 7d41f82bcab4352a60384498412320d0f8a2d134b82ccc0880d4b84eed516fd949fc2868aec94e0e473c59343e14d8c3be528808973b9477bc5c5d5db12a4ece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
